language: node_js
node_js:
- lts/*
# addons:
#   ssh_known_hosts: 
#   - ${DEPLOY_HOST}
#   - ${DEPLOY_HOST_IP_TEN}
cache:
  directories:
  - node_modules
services: docker
install:
- npm install hexo-cli -g
- npm install
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
script:
- hexo g
- make build
- make login
- make push
branches:
  only:
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
# deploy:
#   provider: script
#   script: bash ./deploy.sh
#   skip_cleanup: true